runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /webfonts
  static_dir: webfonts

- url: /quiz.*
  script: quiz.app

- url: /tutor
  script: tutor.app
  
- url: /disciple.*
  script: disciple.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
